=== arctarus44/canopsis/sources/python/schema/etc/schema/patch_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://canopsis.org/patch.json",
  "name": "patch",
  "description": "patch schema for data migration version",

  "links": [
    {
      "href": "#http://canopsis.org/base_schema.json"
    }
  ],

  "type": "object",

  "properties": {

    "add": {
      "type": "object",
      "properties": {
        "op": {
          "type": "string"
        },
        "path": {
          "type": "string"
        },
        "value": {
          "type": "string"
        }
      }
    },

    "replace": {
      "type": "object",
      "properties": {
        "op": {
          "type": "string"
        },
        "path": {
          "type": "string"
        },
        "value": {
          "type": "string"
        }
      }
    },

    "remove": {
      "type": "object",
      "properties": {
        "op": {
          "type": "string"
        },
        "path": {
          "type": "string"
        }
      }
    },

    "copy": {
      "type": "object",
      "properties": {
        "op": {
          "type": "string"
        },
        "from": {
          "type": "string"
        },
        "path": {
          "type": "string"
        }
      }
    },

    "move": {
      "type": "object",
      "properties": {
        "op": {
          "type": "string"
        },
        "from": {
          "type": "string"
        },
        "path": {
          "type": "string"
        }
      }
    }
  }
}

=== arctarus44/canopsis/sources/python/schema/etc/schema/patch.json
{ 
  "add": {
    "op": "add",
    "path": "/properties/essai",
    "value": "type:string"
  },
  "replace": {
    "op": "replace",
    "path": "/properties/info/properties",
    "value": "entity"
  },
  "remove": {
    "op": "remove",
    "path": "/properties/info/properties"
  },
  "copy": {
    "op": "copy",
    "from":"/version",
    "path": "/properties/info/properties"
  },
  "move": {
    "op": "move",
    "from":"/path",
    "path": "/properties/info/properties"
  }
}
